version: "3.3"
services:
  gluetun:
    image: qmcgaw/gluetun:v3.34
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - BOT_TOKEN =
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=openvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - TZ=Asia/Kolkata
      - UPDATER_PERIOD=24h


    ports:
      - "1080:80"
      - "18080:8080" # Optional, depending on your need
    restart: on-failure


  app:
    build: .
    env_file:
      - .env
    network_mode: bridge # Use default bridge network
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"



